### PR TITLE
All hometasks here.

### PR DESCRIPTION
**Pull request by Parsleyka**
There are tasks for lecture1 and lecture2

### CODE REVIEW

**Comment by 2Rman** [comment]
Well, there is lots of code... Did you done all homework from course?

**Comment by Parsleyka** [comment]
> Well, there is lots of code... Did you done all homework from course?

There are only tasks for lecture1 and lecture2

**Review by dkhmylova — APPROVED** [review]
lgfm

**Review by 2Rman — APPROVED** [review]

**Review by ghost — APPROVED** [review]
ok

**Pull request merged**
