### PR TITLE
pageFromGit

### PR DESCRIPTION
**Pull request by zebnitskyMax**
first bonus

### CODE REVIEW

**Review by natal-lia-b — APPROVED** [review]

**Review by natal-lia-b — COMMENTED** [review]
Is it our task? Do we really need to add our site into homework directory?

**Comment by zebnitskyMax** [comment]
i don't no, i decided to do this only my desire)

**Review by Oksalis-s — APPROVED** [review]
Lgfm

**Review by ghost — COMMENTED** [review]
wtf

**Review by Parsleyka — CHANGES_REQUESTED** [review]
We did not have that task

**Comment by natal-lia-b** [comment]
> We did not have that task

i'm sure he can do it. there are no restrictions to make this job, aren't they?

**Review by 2Rman — APPROVED** [review]

**Review by Parsleyka — APPROVED** [review]

**Review by Aomine777 — APPROVED** [review]
lgfm

**Pull request merged**
