### PR TITLE
Task 1 from lecture 3 has been done.

### PR DESCRIPTION
**Pull request by Parsleyka**

### CODE REVIEW

**Review by natal-lia-b — APPROVED** [review]
1 commit with 65 files! hardly understandable :)

**Comment by Parsleyka** [comment]
> 1 commit with 65 files! hardly understandable :)

I just done task 1 from lecture 3 and had a little practice in the code testing)

**Review by natal-lia-b — APPROVED** [review]
looks like a big job

**Review by dkhmylova — APPROVED** [review]
lgfm

**Review by Oksalis-s — APPROVED** [review]
lgfm

**Pull request merged**
