### PR TITLE
Create Lecure1

### PR DESCRIPTION
**Pull request by kleshnya-1**

### CODE REVIEW

**Review by Oksalis-s — DISMISSED** [review]
lgfm

**Review by 2Rman — APPROVED** [review]

**Comment by 2Rman** [comment]
lgfm

**Review by Oksalis-s — APPROVED** [review]
lgfm

**Review by Parsleyka — APPROVED** [review]
lgfm

**Review by Toksel-pixel — APPROVED** [review]

**Comment by Toksel-pixel** [comment]
Lgfm

**Review by zebnitskyMax — APPROVED** [review]
awesome

**Pull request merged**
